### ISSUE TITLE
the example is not working

### ISSUE THREAD

**Issue by sherlockholmes** [lualtek/lualtek-rak3172#1]
I have tried to run the example with arduino and it doesn't compiles.

In file included from C:\Users\sherl\AppData\Local\Temp\.arduinoIDE-unsaved2023529-25376-13m46zo.xua5\Blink\Blink.ino:7:
c:\Users\sherl\Documents\Arduino\libraries\LualtekRAK3172\src/LualtekRAK3172.h:33:27: error: 'SERVICE_LORA_RECEIVE_T' has not been declared
   void onDownlinkReceived(SERVICE_LORA_RECEIVE_T *payload);
                           ^~~~~~~~~~~~~~~~~~~~~~
C:\Users\sherl\AppData\Local\Temp\.arduinoIDE-unsaved2023529-25376-13m46zo.xua5\Blink\Blink.ino:31:1: error: expected ',' or ';' before 'LualtekRAK3172'
 LualtekRAK3172 lltek(APPEUI, APPKEY, MINUTES_20_COMMAND_INDEX);
 ^~~~~~~~~~~~~~
C:\Users\sherl\AppData\Local\Temp\.arduinoIDE-unsaved2023529-25376-13m46zo.xua5\Blink\Blink.ino:65:19: error: variable or field 'recvCallback' declared void
 void recvCallback(SERVICE_LORA_RECEIVE_T *data)
                   ^~~~~~~~~~~~~~~~~~~~~~
C:\Users\sherl\AppData\Local\Temp\.arduinoIDE-unsaved2023529-25376-13m46zo.xua5\Blink\Blink.ino:65:19: error: 'SERVICE_LORA_RECEIVE_T' was not declared in this scope
C:\Users\sherl\AppData\Local\Temp\.arduinoIDE-unsaved2023529-25376-13m46zo.xua5\Blink\Blink.ino:65:43: error: 'data' was not declared in this scope
 void recvCallback(SERVICE_LORA_RECEIVE_T *data)
                                           ^~~~
C:\Users\sherl\AppData\Local\Temp\.arduinoIDE-unsaved2023529-25376-13m46zo.xua5\Blink\Blink.ino:65:43: note: suggested alternative: 'atan'
 void recvCallback(SERVICE_LORA_RECEIVE_T *data)
                                           ^~~~
                                           atan
C:\Users\sherl\AppData\Local\Temp\.arduinoIDE-unsaved2023529-25376-13m46zo.xua5\Blink\Blink.ino: In function 'void powerSensor(int)':
C:\Users\sherl\AppData\Local\Temp\.arduinoIDE-unsaved2023529-25376-13m46zo.xua5\Blink\Blink.ino:34:30: error: 'WB_IO2' was not declared in this scope
 #define POWER_UP_SENSOR_PIN (WB_IO2)
                              ^~~~~~
C:\Users\sherl\AppData\Local\Temp\.arduinoIDE-unsaved2023529-25376-13m46zo.xua5\Blink\Blink.ino:49:11: note: in expansion of macro 'POWER_UP_SENSOR_PIN'
   pinMode(POWER_UP_SENSOR_PIN, OUTPUT);
           ^~~~~~~~~~~~~~~~~~~
C:\Users\sherl\AppData\Local\Temp\.arduinoIDE-unsaved2023529-25376-13m46zo.xua5\Blink\Blink.ino:34:30: note: suggested alternative: 'BIT2'
 #define POWER_UP_SENSOR_PIN (WB_IO2)
                              ^~~~~~
C:\Users\sherl\AppData\Local\Temp\.arduinoIDE-unsaved2023529-25376-13m46zo.xua5\Blink\Blink.ino:49:11: note: in expansion of macro 'POWER_UP_SENSOR_PIN'
   pinMode(POWER_UP_SENSOR_PIN, OUTPUT);
           ^~~~~~~~~~~~~~~~~~~
C:\Users\sherl\AppData\Local\Temp\.arduinoIDE-unsaved2023529-25376-13m46zo.xua5\Blink\Blink.ino: At global scope:
C:\Users\sherl\AppData\Local\Temp\.arduinoIDE-unsaved2023529-25376-13m46zo.xua5\Blink\Blink.ino:65:19: error: variable or field 'recvCallback' declared void
 void recvCallback(SERVICE_LORA_RECEIVE_T *data)
                   ^~~~~~~~~~~~~~~~~~~~~~
C:\Users\sherl\AppData\Local\Temp\.arduinoIDE-unsaved2023529-25376-13m46zo.xua5\Blink\Blink.ino:65:19: error: 'SERVICE_LORA_RECEIVE_T' was not declared in this scope
C:\Users\sherl\AppData\Local\Temp\.arduinoIDE-unsaved2023529-25376-13m46zo.xua5\Blink\Blink.ino:65:43: error: 'data' was not declared in this scope
 void recvCallback(SERVICE_LORA_RECEIVE_T *data)
                                           ^~~~
C:\Users\sherl\AppData\Local\Temp\.arduinoIDE-unsaved2023529-25376-13m46zo.xua5\Blink\Blink.ino:65:43: note: suggested alternative: 'atan'
 void recvCallback(SERVICE_LORA_RECEIVE_T *data)
                                           ^~~~
                                           atan
C:\Users\sherl\AppData\Local\Temp\.arduinoIDE-unsaved2023529-25376-13m46zo.xua5\Blink\Blink.ino: In function 'void setup()':
C:\Users\sherl\AppData\Local\Temp\.arduinoIDE-unsaved2023529-25376-13m46zo.xua5\Blink\Blink.ino:79:29: error: 'RAK_AT_MODE' was not declared in this scope
   debugSerial.begin(115200, RAK_AT_MODE);
                             ^~~~~~~~~~~
C:\Users\sherl\AppData\Local\Temp\.arduinoIDE-unsaved2023529-25376-13m46zo.xua5\Blink\Blink.ino:79:29: note: suggested alternative: 'RMT_RX_MODE'
   debugSerial.begin(115200, RAK_AT_MODE);
                             ^~~~~~~~~~~
                             RMT_RX_MODE
C:\Users\sherl\AppData\Local\Temp\.arduinoIDE-unsaved2023529-25376-13m46zo.xua5\Blink\Blink.ino:82:8: error: 'lltek' was not declared in this scope
   if (!lltek.setup())
        ^~~~~
C:\Users\sherl\AppData\Local\Temp\.arduinoIDE-unsaved2023529-25376-13m46zo.xua5\Blink\Blink.ino:82:8: note: suggested alternative: 'lseek'
   if (!lltek.setup())
        ^~~~~
        lseek
C:\Users\sherl\AppData\Local\Temp\.arduinoIDE-unsaved2023529-25376-13m46zo.xua5\Blink\Blink.ino:89:8: error: 'lltek' was not declared in this scope
   if (!lltek.join())
        ^~~~~
C:\Users\sherl\AppData\Local\Temp\.arduinoIDE-unsaved2023529-25376-13m46zo.xua5\Blink\Blink.ino:89:8: note: suggested alternative: 'lseek'
   if (!lltek.join())
        ^~~~~
        lseek
C:\Users\sherl\AppData\Local\Temp\.arduinoIDE-unsaved2023529-25376-13m46zo.xua5\Blink\Blink.ino:95:3: error: 'api' was not declared in this scope
   api.lorawan.registerRecvCallback(recvCallback);
   ^~~
C:\Users\sherl\AppData\Local\Temp\.arduinoIDE-unsaved2023529-25376-13m46zo.xua5\Blink\Blink.ino:95:36: error: 'recvCallback' was not declared in this scope
   api.lorawan.registerRecvCallback(recvCallback);
                                    ^~~~~~~~~~~~
C:\Users\sherl\AppData\Local\Temp\.arduinoIDE-unsaved2023529-25376-13m46zo.xua5\Blink\Blink.ino:95:36: note: suggested alternative: 'reallocf'
   api.lorawan.registerRecvCallback(recvCallback);
                                    ^~~~~~~~~~~~
                                    reallocf
C:\Users\sherl\AppData\Local\Temp\.arduinoIDE-unsaved2023529-25376-13m46zo.xua5\Blink\Blink.ino:98:8: error: 'lltek' was not declared in this scope
   if (!lltek.setupTimers(*uplinkRoutine))
        ^~~~~
C:\Users\sherl\AppData\Local\Temp\.arduinoIDE-unsaved2023529-25376-13m46zo.xua5\Blink\Blink.ino:98:8: note: suggested alternative: 'lseek'
   if (!lltek.setupTimers(*uplinkRoutine))
        ^~~~~
        lseek
C:\Users\sherl\AppData\Local\Temp\.arduinoIDE-unsaved2023529-25376-13m46zo.xua5\Blink\Blink.ino: In function 'void uplinkRoutine()':
C:\Users\sherl\AppData\Local\Temp\.arduinoIDE-unsaved2023529-25376-13m46zo.xua5\Blink\Blink.ino:124:13: error: 'api' was not declared in this scope
   voltage = api.system.bat.get() * 1000;
             ^~~
In file included from C:\Users\sherl\AppData\Local\Temp\arduino\sketches\A09DBB04DF5256B2A9A22AEA5D8874B6\sketch\Blink.ino.cpp:1:
C:\Users\sherl\AppData\Local\Temp\.arduinoIDE-unsaved2023529-25376-13m46zo.xua5\Blink\Blink.ino:137:44: error: 'lltek' was not declared in this scope
   payloadData[dataSize++] = highByte((int)(lltek.getUplinkInterval() / 1000));
                                            ^~~~~
C:\Users\sherl\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.9\cores\esp32/Arduino.h:93:34: note: in definition of macro 'highByte'
 #define highByte(w) ((uint8_t) ((w) >> 8))
                                  ^
C:\Users\sherl\AppData\Local\Temp\.arduinoIDE-unsaved2023529-25376-13m46zo.xua5\Blink\Blink.ino:137:44: note: suggested alternative: 'lseek'
   payloadData[dataSize++] = highByte((int)(lltek.getUplinkInterval() / 1000));
                                            ^~~~~
C:\Users\sherl\AppData\Local\Arduino15\packages\esp32\hardware\esp32\2.0.9\cores\esp32/Arduino.h:93:34: note: in definition of macro 'highByte'
 #define highByte(w) ((uint8_t) ((w) >> 8))
                                  ^
C:\Users\sherl\AppData\Local\Temp\.arduinoIDE-unsaved2023529-25376-13m46zo.xua5\Blink\Blink.ino: In function 'void loop()':
C:\Users\sherl\AppData\Local\Temp\.arduinoIDE-unsaved2023529-25376-13m46zo.xua5\Blink\Blink.ino:154:3: error: 'api' was not declared in this scope
   api.system.scheduler.task.destroy();
   ^~~

exit status 1

Compilation error: expected ',' or ';' before 'LualtekRAK3172'

**Comment by LasaleFamine** [comment]
Hello @sherlockholmes, you first need to install the RAK board support on Arduino IDE. Please follow the official guide https://docs.rakwireless.com/Product-Categories/wisduo/RAK3172-Module/Quickstart/#-board-support-package-in-arduino-ide
